# Docker compose file for building docker images and running locally

version: '3.8'

services:
  book_catalog:
    build:
     context: ./book_catalog
     dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://sit722_7_1p_user:RXyIcipEtpuFqzCxSd40AdGkkAfnsUPr@dpg-crmd4ui3esus73fr7b20-a.oregon-postgres.render.com/sit722_7_1p


  inventory_management:
    build:
     context: ./inventory_management
     dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
     - DATABASE_URL=postgresql://sit722_7_1p_user:RXyIcipEtpuFqzCxSd40AdGkkAfnsUPr@dpg-crmd4ui3esus73fr7b20-a.oregon-postgres.render.com/sit722_7_1p

